// <auto-generated />
using System;
using LearnifyD1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearnifyD1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250528110654_initialcrete")]
    partial class initialcrete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearnifyD1.Models.Batch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchId"));

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("Slots")
                        .HasColumnType("int");

                    b.Property<DateTime>("time")
                        .HasColumnType("datetime2");

                    b.HasKey("BatchId");

                    b.HasIndex("CourseId");

                    b.ToTable("Batches");

                    b.HasData(
                        new
                        {
                            BatchId = 1,
                            BatchName = "WD-2023-01",
                            CourseId = 1,
                            Slots = 0,
                            time = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BatchId = 2,
                            BatchName = "WD-2023-02",
                            CourseId = 1,
                            Slots = 0,
                            time = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BatchId = 3,
                            BatchName = "MAD-2023-01",
                            CourseId = 2,
                            Slots = 0,
                            time = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BatchId = 4,
                            BatchName = "DS-2023-01",
                            CourseId = 3,
                            Slots = 0,
                            time = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BatchId = 5,
                            BatchName = "GD-2023-01",
                            CourseId = 4,
                            Slots = 0,
                            time = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LearnifyD1.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fees")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseName = "Web Development",
                            Fees = 0
                        },
                        new
                        {
                            CourseId = 2,
                            CourseName = "Mobile App Development",
                            Fees = 0
                        },
                        new
                        {
                            CourseId = 3,
                            CourseName = "Data Science",
                            Fees = 0
                        },
                        new
                        {
                            CourseId = 4,
                            CourseName = "Graphic Design",
                            Fees = 0
                        });
                });

            modelBuilder.Entity("LearnifyD1.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("StudentEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            StudentEmail = "www.wadoodnawaz@gmail.com",
                            StudentName = "Jane"
                        },
                        new
                        {
                            StudentId = 2,
                            StudentEmail = "www.wadoodnawaz@gmail.com",
                            StudentName = "Jane"
                        },
                        new
                        {
                            StudentId = 3,
                            StudentEmail = "www.wadoodnawaz@gmail.com",
                            StudentName = "Jane"
                        },
                        new
                        {
                            StudentId = 4,
                            StudentEmail = "www.wadoodnawaz@gmail.com",
                            StudentName = "Jane"
                        });
                });

            modelBuilder.Entity("LearnifyD1.Models.StudentBatch", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "BatchId");

                    b.HasIndex("BatchId");

                    b.ToTable("StudentBatches", (string)null);

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            BatchId = 1,
                            EnrollmentId = 0,
                            dateTime = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = 2,
                            BatchId = 1,
                            EnrollmentId = 0,
                            dateTime = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = 3,
                            BatchId = 3,
                            EnrollmentId = 0,
                            dateTime = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = 4,
                            BatchId = 4,
                            EnrollmentId = 0,
                            dateTime = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = 1,
                            BatchId = 5,
                            EnrollmentId = 0,
                            dateTime = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LearnifyD1.Models.Batch", b =>
                {
                    b.HasOne("LearnifyD1.Models.Course", "Course")
                        .WithMany("Batches")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LearnifyD1.Models.StudentBatch", b =>
                {
                    b.HasOne("LearnifyD1.Models.Batch", "batch")
                        .WithMany("studentbatches")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnifyD1.Models.Student", "student")
                        .WithMany("studentBatches")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("batch");

                    b.Navigation("student");
                });

            modelBuilder.Entity("LearnifyD1.Models.Batch", b =>
                {
                    b.Navigation("studentbatches");
                });

            modelBuilder.Entity("LearnifyD1.Models.Course", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("LearnifyD1.Models.Student", b =>
                {
                    b.Navigation("studentBatches");
                });
#pragma warning restore 612, 618
        }
    }
}
